version: '3.8'

services:
  portal:
    image: portal-application
    build: .
    container_name: portal-application
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/ink
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=69gidadi
      - FILE_STORAGE_PATH=/app/file-storage
      - APP_YANDEX_KEY=y0__xCOxOOAAhjblgMgqZ7f_hTBVYkncrd66FLS0scdlgPl_MOsgw
      - CLIENT_ID=31d7d28d65964d05bd6a198f96a30552
      - CLIENT_SECRET=f31972f9448d4422b79140de954e7869
      # URL для интеграции с OnlyOffice внутри сети
      - ONLYOFFICE_URL=http://onlyoffice:80
      - ONLYOFFICE_JWT_SECRET=supersecret
      - APP_SERVER_URL=http://localhost:8083/web-apps/apps/api/documents/api.js
    volumes:
      - ./file-storage:/app/file-storage
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - portal_net

  onlyoffice:
    image: onlyoffice/documentserver:5.5.1   # версия без лимита подключений
    container_name: onlyoffice
    restart: always
    ports:
      - "8083:80"   # доступ снаружи по http://localhost:8083
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=supersecret
      - JWT_HEADER=Authorization
    networks:
      - portal_net
  database:
    image: postgres:16-alpine
    container_name: database
    environment:
      POSTGRES_DB: ink
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 69gidadi
    ports:
      - "5435:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - portal_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ink" ]  # юзер должен совпадать
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  portal_net:
    driver: bridge
